CC = g++

cn: CyclicNumbers.cpp
	$(CC) $^ -o cyclic_numbers

kc: KhinchinConstants.cpp
	$(CC) $^ -o khinchin_constants

pe: PrimeEcho.cpp
	$(CC) $^ -o prime_echo

ss: SumOfSquares.cpp
	$(CC) $^ -o sum_of_squares

all:
	make cn
	make kc
	make pe
	make ss
